apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: wc-hello
  annotations:
    version: v0.0.1

spec:
  components:
    - name: filer
      type: component
      properties:
        image: file://filer/build/filer_s.wasm
      traits:
        - type: spreadscaler
          properties:
            instances: 1
        
        - type: link
          properties:
            target:
              name: fs-provider
            namespace: wasmcloud
            package: example
            interfaces: [fs-storage]

        - type: link
          properties:
            target:
              name: nats
            namespace: wasmcloud
            package: messaging
            interfaces: [consumer]

    - name: listener
      type: component
      properties:
        image: file://listener/build/listener_s.wasm
      traits:
        - type: spreadscaler
          properties:
            instances: 1
        
        - type: link
          properties:
            target:
              name: fs-provider
            namespace: wasmcloud
            package: example
            interfaces: [fs-storage]

        - type: link
          properties:
            target:
              name: nats
            namespace: wasmcloud
            package: messaging
            interfaces: [consumer]

    - name: httpserver
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:0.25.0
      traits:
        - type: link
          properties:
            target:
              name: filer
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source:
              config:
                - name: default-http
                  properties:
                    address: 0.0.0.0:8000

    - name: nats
      type: capability
      properties:
        image: ghcr.io/wasmcloud/messaging-nats:0.24.0
      traits:
        - type: link
          properties:
            target:
              name: listener
            namespace: wasmcloud
            package: messaging
            interfaces: [handler]
            source:
              config:
                - name: simple-subscription
                  properties:
                    subscriptions: hello.event

    - name: fs-provider
      type: capability
      properties:
        image: file://storage-provider/build/fs-storage-provider.par.gz