name = "listener"
version = "0.1.0"
language = "rust"
type = "component"

[component]
wit_world = "listener"
wasm_target = "wasm32-wasip2"

[overrides]
"wasmcloud:example" = { path = "../storage-provider/wit" }